# Generated by Django 3.0.6 on 2020-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200525_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='github not added'),
            preserve_default=False,
        ),
    ]
