# Generated by Django 3.0.6 on 2020-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='language',
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.ManyToManyField(to='language.Language'),
        ),
    ]
